export const waarden = [
  { id: 'klaretaal', label: 'Klare taal', motto: 'Zeg wat je bedoelt, zonder kleine lettertjes' },
  { id: 'samen', label: 'Samen slimmer', motto: 'Eén team, ook met onze partners' },
  { id: 'regelen', label: 'We regelen het', motto: 'Afspraak is afspraak, en dan liever vandaag' },
  { id: 'nieuwsgierig', label: 'Nieuwsgierig', motto: '"Zo doen we dat altijd" is nooit een argument' },
  { id: 'betrouwbaar', label: 'Betrouwbaar, altijd', motto: 'Mensen vertrouwen ons hun grootste financiële beslissing toe' },
  { id: 'service', label: 'Service is sales', motto: 'We hebben geen salesafdeling, we hebben accountmanagement' },
  { id: 'momentje', label: 'Blinqx-momentje', motto: 'Een klein gebaar dat de ander nog maanden onthoudt' },
];

export const groepen = [
  { id: 'kort', label: 'Kort', teksten: [
    'Dankjewel. Gewoon, omdat het verdiend is.',
    'Even een moment van waardering.',
    'Bedankt, kanjer.',
    'Met dank en een glimlach.',
    'Zonder jou geen wij. Dankjewel.',
    'Even een moment van dank. Nu terug naar het werk.',
    'Merci, dankjewel, thanks — in elke taal gemeend.',
    'Dankjewel. Je mag het ons lang blijven aandoen.',
    'Bedankt. Jij bent de reden dat we dit doen. (En de koffie.)',
  ]},
  { id: 'klanten', label: 'Klanten', teksten: [
    'Bedankt dat je voor ons hebt gekozen — we zijn er ook morgen voor je.',
    'Fijn dat je bij ons bent. Dankjewel voor het vertrouwen.',
    'Een tevreden klant is ons mooiste compliment. Bedankt.',
    'Bedankt voor het vertrouwen in ons – we waarderen de samenwerking enorm.',
    'Dank voor de prettige samenwerking van de afgelopen periode.',
    'Fijn dat u opnieuw voor ons heeft gekozen. Dank u wel.',
    'Bedankt voor uw geduld tijdens de overgang; het wordt gewaardeerd.',
    'Dank voor uw heldere feedback – daar worden we beter van.',
    'Bedankt dat u de tijd nam voor ons gesprek vandaag.',
    'Hartelijk dank voor de aanbeveling aan uw relatie.',
    'Dank voor het snelle aanleveren van de stukken, dat hielp enorm.',
    'Bedankt voor uw open houding tijdens de implementatie.',
    'Fijn dat we dit samen tot een goed einde hebben gebracht. Dank!',
    'Dank voor uw kritische vragen – die scherpten ons voorstel aan.',
    'Bedankt voor de constructieve evaluatie, we pakken de punten op.',
    'Dank voor uw flexibiliteit rondom de planning.',
    'Bedankt voor de fijne kennismaking, we kijken uit naar het vervolg.',
    'Hartelijk dank voor de jarenlange trouwe samenwerking.',
    'Dank dat u ons hebt betrokken bij dit traject.',
    'Bedankt voor uw snelle reactie, daarmee bleven we op schema.',
    'Dank voor de gastvrijheid bij ons bezoek aan uw kantoor.',
    'Bedankt voor het delen van uw ervaringen met het platform.',
    'Dank voor uw vertrouwen in de nieuwe koppeling – we houden u op de hoogte.',
  ]},
  { id: 'samenwerking', label: 'Samenwerking', teksten: [
    'Bedankt voor de fijne samenwerking — op naar het volgende hoofdstuk samen.',
    'Jouw vertrouwen maakt ons werk de moeite waard. Dankjewel.',
    'Samenwerken met jou voelt nooit als werk. Bedankt daarvoor.',
    'Dank voor het meedenken, het meebewegen en het vertrouwen.',
    'Een goede relatie verdient een goed bedankje. Bij deze.',
  ]},
  { id: 'collegas', label: "Collega's", teksten: [
    'Bedankt voor je inzet — het wordt gezien en gewaardeerd.',
    'Jij bent goud waard. En dat mag best eens gezegd worden.',
    'Zonder jou was dit niet gelukt. Heel erg bedankt.',
    'Dank voor je harde werk, je humor en je nuchtere blik.',
    'Een klein gebaar voor een grote bijdrage. Dankjewel.',
    'Dank voor je hulp vandaag, zonder jou was het niet gelukt.',
    'Bedankt voor het overnemen tijdens mijn afwezigheid.',
    'Fijn dat je even meekeek – dank je.',
    'Dank voor je scherpe blik op het stuk.',
    'Bedankt voor het snelle regelen van de afspraak.',
    'Dank voor je eerlijke feedback, dat waardeer ik.',
    'Bedankt voor de voorbereiding van het overleg, dat scheelde veel tijd.',
    'Dank voor je flexibiliteit in de planning deze week.',
    'Fijn dat je dit hebt opgepakt, top gedaan.',
    'Bedankt voor het delen van je kennis met het team.',
    'Dank voor je inzet op het project – het resultaat mag er zijn.',
    'Bedankt voor je positieve energie tijdens de drukke dagen.',
    'Dank voor het doorzetten toen het even tegenzat.',
    'Bedankt voor je heldere uitleg aan de klant.',
    'Fijn dat je altijd bereikbaar bent, dank je.',
  ]},
  { id: 'partners', label: 'Partners', teksten: [
    'Bedankt voor de goede afstemming, zo werkt een keten pas echt.',
    'Dank voor jullie inzet op de gezamenlijke roadmap.',
    'Bedankt voor de snelle schakel op de technische vraag.',
    'Fijn dat we elkaar scherp houden – dank daarvoor.',
    'Dank voor het meedenken over het klantproces.',
    'Bedankt voor jullie bijdrage aan de presentatie.',
    'Dank voor de prettige onderhandeling en het bereikte resultaat.',
    'Bedankt voor het openstellen van jullie data voor de pilot.',
    'Dank voor jullie geduld bij het uitwerken van de contractdetails.',
    'Bedankt voor de uitnodiging, het was een waardevolle sessie.',
  ]},
  { id: 'bestuur', label: 'Bestuur / vereniging', teksten: [
    'Dank voor je bijdrage aan de vergadering en de heldere stukken.',
    'Bedankt voor het organiseren van het congres, het liep gesmeerd.',
    'Dank voor je inzet als spreker, de reacties waren erg positief.',
    'Bedankt voor het meedenken over de begroting.',
    'Dank voor je betrokkenheid bij de vereniging het afgelopen jaar.',
  ]},
  { id: 'afscheid', label: 'Afscheid / mijlpaal', teksten: [
    'Dank voor alles wat je hebt gebracht. We gaan je missen.',
    'Bedankt voor de jaren, de lachmomenten en de resultaten.',
    'Het was een voorrecht om met jou te werken. Alle goeds.',
  ]},
  { id: 'hypotheekbos', label: 'Hypotheekbos', teksten: [
    'Bedankt voor je vertrouwen – als dank planten we een boom voor je in het Hypotheekbos. Zo groeit onze samenwerking letterlijk door.',
    'Je hypotheek is geregeld, en er staat nu ook een boom op jouw naam in het Hypotheekbos. Dank je wel!',
    'Dank voor de fijne samenwerking. Wij planten een boom in het Hypotheekbos, en die blijft langer staan dan je rentevaste periode.',
    'Een huis is een plek om te wortelen. Als dank voor je vertrouwen laten we ook een boom wortelen in het Hypotheekbos.',
    'Bedankt! Je handtekening zorgde niet alleen voor een woning, maar ook voor een boom in het Hypotheekbos.',
    'Wij bouwen aan jouw toekomst, en samen met jou aan een groenere: er staat een boom voor je klaar in het Hypotheekbos.',
    'Dank voor je vertrouwen. Terwijl je hypotheek aflost, groeit jouw boom in het Hypotheekbos.',
    'Welkom thuis – en welkom in het Hypotheekbos, waar we als dank een boom voor je planten.',
    'Kleine stap voor jou, grote stap voor het bos: dank je wel, jouw boom staat in het Hypotheekbos.',
    'Bedankt voor de samenwerking. Plant je met ons mee? Jouw boom wacht in het Hypotheekbos.',
  ]},
  { id: 'knipoog', label: 'Met een knipoog', teksten: [
    'Bedankt dat je ons uitkoos. We beloven het niet naar ons hoofd te laten stijgen. (Een beetje maar.)',
    'Je bent officieel onze favoriete klant. Niet doorvertellen aan de anderen.',
    'Dankjewel voor het vertrouwen — we hebben er geen minuut van geslapen. Grapje. Wel keihard gewerkt.',
    'Een klant als jij verdient chocolade. Dus: alsjeblieft.',
    'Bedankt voor de samenwerking. Zonder jou zaten we hier maar wat koffie te drinken.',
    'Jij maakt ons werk leuk. Dat is meer dan ons koffiezetapparaat ooit voor elkaar kreeg.',
    'Klanten als jij zouden verplicht moeten zijn. Bedankt!',
    'We hebben geen loyaliteitsprogramma, dus krijg je gewoon dit. Dankjewel.',
    'Fijn dat je ons hebt gevonden. Nog fijner dat je bent gebleven.',
    'Bedankt voor je geduld, je vragen en je vertrouwen. Vooral dat geduld.',
    'Sommige klanten worden relaties. Jij hoort bij die tweede groep. Dankjewel.',
    'We zeggen niet vaak "dankjewel" met een cadeautje erbij. Voel je dus bijzonder.',
    'Bedankt dat je met ons in zee ging — we hebben je droog gehouden, toch?',
    'Jij zei ja. Wij zeiden: daar gaan we iets moois van maken. Bedankt voor het vertrouwen.',
    'Voor de klant die altijd op tijd betaalt: dit is speciaal voor jou. Dankjewel.',
  ]},
];
